### ISSUE TITLE
Sync between computers

### ISSUE THREAD

**Issue by mgsotelo** [hjohnson12/Kanban-Tasker#13]
Hi, I was wondering if it could be possible to sync the database between 2 local pcs or maybe using microsoft account. Btw, great software!

**Comment by hjohnson12** [comment]
Hi @mgsotelo ! Thank you :) 

I've actually been working on options for multiple database types with another user, like MSSQL and MySQL as well as the current option SQLite, so that users are able to point their databases to those servers if they use them. On most of my latest branches, besides master, the Endpoint configuration is already set to MSSQL since that's been my latest testing area. Those changes are not setup for production on the Microsoft Store yet, but everything works so far on my dev branches if you'd like to use those.

For the users that don't use MSSQL or MySQL, I'm hoping to find a way for them to backup their local database or some sort of sync, but I seem to be very limited on my options with SQLite using my newest implementations and what I'm able to use API-wise in UWP!

I'll keep this request here and update it when I get close to production ready on those changes :)

**Comment by hailstorm75** [comment]
A different option would be to sync to OneDrive - allow users to specify sqlite file location.

**Comment by nagarjunajava10** [comment]
I have created a windows task and pointed to a custom batch file to take backup everyday at sometime. This batch file will copy and always override at the destination location. Here in my case the destination location is my onedrive specific folder :)

**Comment by hjohnson12** [comment]
Hey everyone! Sorry it's been a while, it's been a very extraordinary year so far. I have released v1.2.0 recently in the store and it includes services to backup and restore with OneDrive and your preferred Microsoft Account. You can sign out and sync with another account as well too ☺

I hope it works well for you and please feel free to reach out with any questions or issues! 

Stay well!
