### ISSUE TITLE
Column Collapse sometimes does not work

### ISSUE THREAD

**Issue by Natomix** [hjohnson12/Kanban-Tasker#3]
Sometimes when clicking the left arrow < to collapse a column it does nothing and it takes a few clicks,
it seems to happen when I click on the arrow itself but works normally when I click around the arrow.

EDIT: I have no issue opening the column, just when collapsing it.

**Comment by Natomix** [comment]
Would it also be possible to save the collapsed state so it stays collapsed after re-opening Kanban Tasker? That would be a nice quality of life feature. :)

**Comment by hjohnson12** [comment]
Hi, I'm sorry for the late reply!

So, I am aware of the non collapse of the column when selecting the arrow, that's actually a part of the control I'm using from Syncfusion. I'm able to edit the data template for the custom UI, but I'm not able to do a lot with the back-end such as the code that collapses that column, or the clickable areas because they're not open sourced. I ran into this during development, but the images below show the area around the icon that are clickable (excluding the icon). Typically I just click slightly to the left of the icon and it always works for me :) I hope this can be of some help for the meantime!

![image](https://user-images.githubusercontent.com/20372914/63604916-e5a5e200-c59a-11e9-8d30-ca591fe44652.png) ![image](https://user-images.githubusercontent.com/20372914/63604931-ec345980-c59a-11e9-9fb2-25af282b669b.png)

Regarding question two, I actually tried this out, but was running into issues where the property wouldn't accept my style bindings when first running the application, which I think is due to a workaround given when the collapse column template wasn't working correctly on collapse. I hadn't reported this back then, but I will let them know and hopefully they can do something! This is actually related to an issue in Kanban Tasker where if you have a column collapsed, and you update a task in another column, sometimes the collapsed column template wants to revert to Syncfusion's built-in one 🙃 If I get any response from them, I'll be sure to fill you in :)
